version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  api-service:
    env_file:
      - .env.docker
  diagnosis-mongodb:
    image: mongo
    container_name: diagnosis-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hophuchieu
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - ./data/db:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  chatbot:
    build:
      context: ./apps/chatbot-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
